apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: gcr.io/k8s-staging-cloud-provider-ibm/ibm-powervs-block-csi-driver
    newTag: v0.1.0-alpha.3
  - name: k8s.gcr.io/sig-storage/csi-provisioner
    newTag: v3.1.0
  - name: k8s.gcr.io/sig-storage/csi-attacher
    newTag: v3.4.0
  - name: k8s.gcr.io/sig-storage/csi-resizer
    newTag: v1.4.0
  - name: k8s.gcr.io/sig-storage/livenessprobe
    newTag: v2.6.0
  - name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    newTag: v2.5.0
