apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: registry.k8s.io/cloud-provider-ibm/ibm-powervs-block-csi-driver
  newTag: v0.11.0
- name: registry.k8s.io/sig-storage/csi-provisioner
  newTag: v6.1.0
- name: registry.k8s.io/sig-storage/csi-attacher
  newTag: v4.9.0
- name: registry.k8s.io/sig-storage/csi-resizer
  newTag: v2.0.0
- name: registry.k8s.io/sig-storage/livenessprobe
  newTag: v2.17.0
- name: registry.k8s.io/sig-storage/csi-node-driver-registrar
  newTag: v2.15.0
resources:
- ../../base
